name: code checks

on:
  push:
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6]
    steps:
      - uses: actions/checkout@v3
      - name: install python ${{ matrix.python-version }}
        uses: MatteoH2O1999/setup-python@v1
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
          python-version: ${{ matrix.python-version }}
      - name: install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: run flake8
        run: flake8 project
      - name: run mypy
        run: mypy project
