name: code checks

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
    steps:
      - uses: actions/checkout@v3
      - name: install python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          mypy --install-types --non-interactive
      - name: run flake8
        run: flake8 project
      - name: run mypy
        run: mypy project
